[versions]
agp = "9.0.0"
carousellayoutmanager = "1.4.6"
compose = "2.10.0"
facebookLogin = "18.1.3"
firebaseAuth = "24.0.1"
firebaseBom = "34.8.0"
firebaseFirestore = "26.1.0"
firebaseStorage = "22.0.1"
generativeai = "0.9.0"
glide = "5.0.5"
googleApiClient = "2.8.1"
googleApiServicesCalendar = "v3-rev20220715-2.0.0"
googleid = "1.1.1"
googleOauthClientJetty = "1.39.0"
grpcOkhttp = "1.78.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
lottie = "6.7.1"
material = "1.13.0"
activity = "1.12.2"
constraintlayout = "2.2.1"
googleServices = "4.4.2"
firebaseDatabase = "22.0.1"
annotation = "1.9.1"
lifecycleLivedataKtx = "2.10.0"
lifecycleViewmodelKtx = "2.10.0"
navigationFragment = "2.9.6"
navigationUi = "2.9.6"
legacySupportV4 = "1.0.0"
kotlin = "2.2.10"
coreKtx = "1.17.0"
playServicesAuth = "21.5.0"
recyclerviewAnimators = "4.0.2"
truetimeAndroid = "3.5"
ucrop = "2.2.8"

[libraries]
carousellayoutmanager = { module = "com.mig35:carousellayoutmanager", version.ref = "carousellayoutmanager" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
compose = { module = "com.kizitonwose.calendar:compose", version.ref = "compose" }
facebook-login = { module = "com.facebook.android:facebook-login", version.ref = "facebookLogin" }
firebase-auth = { module = "com.google.firebase:firebase-auth", version.ref = "firebaseAuth" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore", version.ref = "firebaseFirestore" }
firebase-storage = { module = "com.google.firebase:firebase-storage", version.ref = "firebaseStorage" }
generativeai = { module = "com.google.ai.client.generativeai:generativeai", version.ref = "generativeai" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
google-api-client = { module = "com.google.api-client:google-api-client", version.ref = "googleApiClient" }
google-api-services-calendar = { module = "com.google.apis:google-api-services-calendar", version.ref = "googleApiServicesCalendar" }
google-oauth-client-jetty = { module = "com.google.oauth-client:google-oauth-client-jetty", version.ref = "googleOauthClientJetty" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }
grpc-okhttp = { module = "io.grpc:grpc-okhttp", version.ref = "grpcOkhttp" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
google-services = { group = "com.google.gms", name = "google-services", version.ref = "googleServices" }
firebase-database = { group = "com.google.firebase", name = "firebase-database", version.ref = "firebaseDatabase" }
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacySupportV4" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
recyclerview-animators = { module = "jp.wasabeef:recyclerview-animators", version.ref = "recyclerviewAnimators" }
truetime-android = { module = "com.github.instacart:truetime-android", version.ref = "truetimeAndroid" }
ucrop = { module = "com.github.yalantis:ucrop", version.ref = "ucrop" }
view = { module = "com.kizitonwose.calendar:view", version.ref = "compose" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

